

export const THEME_COLORS = {
  primary: '#2f5cd6',
  hover: '#193685',
  white: '#ffffff',
  darkBg: '#111827', // Gray 900
  darkSurface: '#1f2937', // Gray 800
  darkText: '#f3f4f6', // Gray 100
};

export const NAVIGATION_ITEMS = [
  { labelKey: 'support', iconLetter: 'S', id: 'support' },
  { labelKey: 'about', iconLetter: 'W', id: 'about' },
  { labelKey: 'help', iconLetter: 'H', id: 'help' },
];

export const ALL_CAR_MODELS = [
  // TOYOTA
  { ar: 'تويوتا كامري', en: 'Toyota Camry' },
  { ar: 'تويوتا كورولا', en: 'Toyota Corolla' },
  { ar: 'تويوتا ياريس', en: 'Toyota Yaris' },
  { ar: 'تويوتا أفالون', en: 'Toyota Avalon' },
  { ar: 'تويوتا بريوس', en: 'Toyota Prius' },
  { ar: 'تويوتا راف 4', en: 'Toyota RAV4' },
  { ar: 'تويوتا لاند كروزر', en: 'Toyota Land Cruiser' },
  { ar: 'تويوتا لاند كروزر برادو', en: 'Toyota Land Cruiser Prado' },
  { ar: 'تويوتا هايلاندر', en: 'Toyota Highlander' },
  { ar: 'تويوتا تاكوما', en: 'Toyota Tacoma' },
  { ar: 'تويوتا تندرا', en: 'Toyota Tundra' },
  { ar: 'تويوتا هايلوكس', en: 'Toyota Hilux' },
  { ar: 'تويوتا فور رنر', en: 'Toyota 4Runner' },
  { ar: 'تويوتا سيكويا', en: 'Toyota Sequoia' },
  { ar: 'تويوتا سيينا', en: 'Toyota Sienna' },
  { ar: 'تويوتا ألفارد', en: 'Toyota Alphard' },
  { ar: 'تويوتا إنوفا', en: 'Toyota Innova' },
  { ar: 'تويوتا فورتشنر', en: 'Toyota Fortuner' },
  { ar: 'تويوتا أف جي كروزر', en: 'Toyota FJ Cruiser' },
  { ar: 'تويوتا هارير', en: 'Toyota Harrier' },
  { ar: 'تويوتا سوبرا', en: 'Toyota Supra' },
  { ar: 'تويوتا جي آر 86', en: 'Toyota GR86' },
  { ar: 'تويوتا جي آر كورولا', en: 'Toyota GR Corolla' },
  { ar: 'تويوتا بيلتا', en: 'Toyota Belta' },
  { ar: 'تويوتا زي 4 إكس', en: 'Toyota bZ4X' },
  { ar: 'تويوتا إيكو', en: 'Toyota Echo' },
  { ar: 'تويوتا ماتريكس', en: 'Toyota Matrix' },
  { ar: 'تويوتا سيليكا', en: 'Toyota Celica' },
  { ar: 'تويوتا كامري سولارا', en: 'Toyota Camry Solara' },
  { ar: 'تويوتا كافاليير', en: 'Toyota Cavalier' },
  { ar: 'تويوتا أوربان كروزر', en: 'Toyota Urban Cruiser' },
  { ar: 'تويوتا كراون', en: 'Toyota Crown' },
  { ar: 'تويوتا راوم', en: 'Toyota Raum' },
  { ar: 'تويوتا راكتس', en: 'Toyota Ractis' },
  { ar: 'تويوتا بيكنيك', en: 'Toyota Picnic' },
  { ar: 'تويوتا أستيما', en: 'Toyota Estima' },
  { ar: 'تويوتا بروبوكس', en: 'Toyota Probox' },
  { ar: 'تويوتا أوريون', en: 'Toyota Aurion' },
  { ar: 'تويوتا فايتز', en: 'Toyota Vitz' },
  { ar: 'تويوتا كارينا إي', en: 'Toyota Carina E' },
  { ar: 'تويوتا كرن', en: 'Toyota Curren' },
  { ar: 'تويوتا مارك إكس', en: 'Toyota Mark X' },
  
  // VOLKSWAGEN
  { ar: 'فولكس واجن جولف', en: 'Volkswagen Golf' },
  { ar: 'فولكس واجن باسات', en: 'Volkswagen Passat' },
  { ar: 'فولكس واجن تيجوان', en: 'Volkswagen Tiguan' },
  { ar: 'فولكس واجن طوارق', en: 'Volkswagen Touareg' },
  { ar: 'فولكس واجن بيتل', en: 'Volkswagen Beetle' },

  // FORD
  { ar: 'فورد إف-150', en: 'Ford F-150' },
  { ar: 'فورد موستنج', en: 'Ford Mustang' },
  { ar: 'فورد اكسبلورر', en: 'Ford Explorer' },
  { ar: 'فورد تورس', en: 'Ford Taurus' },
  { ar: 'فورد اكسبدشن', en: 'Ford Expedition' },
  { ar: 'فورد رينجر', en: 'Ford Ranger' },

  // HONDA
  { ar: 'هوندا أكورد', en: 'Honda Accord' },
  { ar: 'هوندا سيفيك', en: 'Honda Civic' },
  { ar: 'هوندا سي آر-في', en: 'Honda CR-V' },
  { ar: 'هوندا بايلوت', en: 'Honda Pilot' },
  { ar: 'هوندا أوديسي', en: 'Honda Odyssey' },

  // HYUNDAI
  { ar: 'هيونداي سوناتا', en: 'Hyundai Sonata' },
  { ar: 'هيونداي النترا', en: 'Hyundai Elantra' },
  { ar: 'هيونداي توسان', en: 'Hyundai Tucson' },
  { ar: 'هيونداي سنتافي', en: 'Hyundai Santa Fe' },
  { ar: 'هيونداي أكسنت', en: 'Hyundai Accent' },

  // KIA
  { ar: 'كيا اوبتيما (K5)', en: 'Kia Optima (K5)' },
  { ar: 'كيا سبورتاج', en: 'Kia Sportage' },
  { ar: 'كيا سورينتو', en: 'Kia Sorento' },
  { ar: 'كيا ريو', en: 'Kia Rio' },
  { ar: 'كيا تيلورايد', en: 'Kia Telluride' },

  // NISSAN
  { ar: 'نيسان ألتيما', en: 'Nissan Altima' },
  { ar: 'نيسان ماكسيما', en: 'Nissan Maxima' },
  { ar: 'نيسان باترول', en: 'Nissan Patrol' },
  { ar: 'نيسان صني', en: 'Nissan Sunny' },
  { ar: 'نيسان باثفندر', en: 'Nissan Pathfinder' },

  // CHEVROLET
  { ar: 'شيفروليه تاهو', en: 'Chevrolet Tahoe' },
  { ar: 'شيفروليه سوبربان', en: 'Chevrolet Suburban' },
  { ar: 'شيفروليه كابريس', en: 'Chevrolet Caprice' },
  { ar: 'شيفروليه ماليبو', en: 'Chevrolet Malibu' },
  { ar: 'شيفروليه كمارو', en: 'Chevrolet Camaro' },
  { ar: 'شيفروليه كورفيت', en: 'Chevrolet Corvette' },

  // MERCEDES-BENZ
  { ar: 'مرسيدس سي كلاس', en: 'Mercedes-Benz C-Class' },
  { ar: 'مرسيدس إي كلاس', en: 'Mercedes-Benz E-Class' },
  { ar: 'مرسيدس إس كلاس', en: 'Mercedes-Benz S-Class' },
  { ar: 'مرسيدس جي كلاس', en: 'Mercedes-Benz G-Class' },
  { ar: 'مرسيدس جي أل إي', en: 'Mercedes-Benz GLE' },

  // BMW
  { ar: 'بي إم دبليو الفئة 3', en: 'BMW 3 Series' },
  { ar: 'بي إم دبليو الفئة 5', en: 'BMW 5 Series' },
  { ar: 'بي إم دبليو الفئة 7', en: 'BMW 7 Series' },
  { ar: 'بي إم دبليو إكس 5', en: 'BMW X5' },
  { ar: 'بي إم دبليو إكس 6', en: 'BMW X6' },

  // AUDI
  { ar: 'أودي A4', en: 'Audi A4' },
  { ar: 'أودي A6', en: 'Audi A6' },
  { ar: 'أودي A8', en: 'Audi A8' },
  { ar: 'أودي Q7', en: 'Audi Q7' },
  { ar: 'أودي Q8', en: 'Audi Q8' },

  // TESLA
  { ar: 'تسلا موديل S', en: 'Tesla Model S' },
  { ar: 'تسلا موديل 3', en: 'Tesla Model 3' },
  { ar: 'تسلا موديل X', en: 'Tesla Model X' },
  { ar: 'تسلا موديل Y', en: 'Tesla Model Y' },
  { ar: 'تسلا سايبرتراك', en: 'Tesla Cybertruck' },

  // FERRARI
  { ar: 'فيراري 488', en: 'Ferrari 488' },
  { ar: 'فيراري روما', en: 'Ferrari Roma' },
  { ar: 'فيراري إف 8', en: 'Ferrari F8' },
  { ar: 'فيراري بورتوفينو', en: 'Ferrari Portofino' },

  // PORSCHE
  { ar: 'بورش 911', en: 'Porsche 911' },
  { ar: 'بورش كايين', en: 'Porsche Cayenne' },
  { ar: 'بورش باناميرا', en: 'Porsche Panamera' },
  { ar: 'بورش تايكان', en: 'Porsche Taycan' },

  // BYD
  { ar: 'بي واي دي هان', en: 'BYD Han' },
  { ar: 'بي واي دي تانغ', en: 'BYD Tang' },
  { ar: 'بي واي دي أتو 3', en: 'BYD Atto 3' },
  { ar: 'بي واي دي سيل', en: 'BYD Seal' },

  // SUZUKI
  { ar: 'سوزوكي سويفت', en: 'Suzuki Swift' },
  { ar: 'سوزوكي فيتارا', en: 'Suzuki Vitara' },
  { ar: 'سوزوكي جيمني', en: 'Suzuki Jimny' },
  { ar: 'سوزوكي بالينو', en: 'Suzuki Baleno' },

  // MITSUBISHI
  { ar: 'ميتسوبيشي باجيرو', en: 'Mitsubishi Pajero' },
  { ar: 'ميتسوبيشي لانسر', en: 'Mitsubishi Lancer' },
  { ar: 'ميتسوبيشي أوتلاندر', en: 'Mitsubishi Outlander' },
  { ar: 'ميتسوبيشي إل200', en: 'Mitsubishi L200' },

  // SUBARU
  { ar: 'سوزوكي إمبريزا', en: 'Subaru Impreza' },
  { ar: 'سوبارو ليجاسي', en: 'Subaru Legacy' },
  { ar: 'سوبارو فورستر', en: 'Subaru Forester' },
  { ar: 'سوبارو أوت باك', en: 'Subaru Outback' },

  // MAZDA
  { ar: 'مازدا 6', en: 'Mazda 6' },
  { ar: 'مازدا 3', en: 'Mazda 3' },
  { ar: 'مازدا سي إكس-5', en: 'Mazda CX-5' },
  { ar: 'مازدا سي إكس-9', en: 'Mazda CX-9' },

  // RAM
  { ar: 'رام 1500', en: 'RAM 1500' },
  { ar: 'رام 2500', en: 'RAM 2500' },
  { ar: 'رام تي آر إكس', en: 'RAM TRX' },

  // JEEP
  { ar: 'جيب رانجلر', en: 'Jeep Wrangler' },
  { ar: 'جيب جراند شيروكي', en: 'Jeep Grand Cherokee' },
  { ar: 'جيب جلاديتور', en: 'Jeep Gladiator' },

  // LEXUS
  { ar: 'لكزس ES', en: 'Lexus ES' },
  { ar: 'لكزس LS', en: 'Lexus LS' },
  { ar: 'لكزس RX', en: 'Lexus RX' },
  { ar: 'لكزس LX', en: 'Lexus LX' },
  { ar: 'لكزس IS', en: 'Lexus IS' },

  // VOLVO
  { ar: 'فولفو XC90', en: 'Volvo XC90' },
  { ar: 'فولفو XC60', en: 'Volvo XC60' },
  { ar: 'فولفو S90', en: 'Volvo S90' },

  // LUCID
  { ar: 'لوسيد آير', en: 'Lucid Air' },
  { ar: 'لوسيد جرافيتي', en: 'Lucid Gravity' },

  // GENERAL MOTORS (Other Brands/General)
  { ar: 'جي إم سي يوكون', en: 'GMC Yukon' },
  { ar: 'جي إم سي سييرا', en: 'GMC Sierra' },
  { ar: 'كاديلاك إسكاليد', en: 'Cadillac Escalade' },
  { ar: 'هامر إي في', en: 'Hummer EV' }
];

export const TRANSLATIONS = {
  ar: {
    appTitle: 'كارفا',
    login: 'تسجيل الدخول',
    signup: 'أنشاء حساب',
    guest: 'استمرار ك ضيف',
    support: 'الدعم الفني',
    about: 'من نحن؟',
    help: 'مساعدة',
    loginTitle: 'تسجيل الدخول',
    loginIdentifier: 'اسم المستخدم أو البريد الإلكتروني',
    password: 'كلمة المرور',
    enter: 'دخول',
    roleTitle: 'نورتنا! علمنا عنك',
    roleSat7a: 'سطحة',
    roleUser: 'أنا مستخدم',
    roleWorkshop: 'أنا ورشة',
    detailsTitle: 'بيانات',
    nameLabel: 'أسمك؟',
    usernameLabel: 'اليوزر؟',
    emailLabel: 'الأيميل؟',
    passwordLabel: 'الباسوورد؟',
    confirmPasswordLabel: 'الباسوورد مرة ثانية؟',
    register: 'تسجيل',
    verifyTitle: 'تأكيد الحساب',
    verifyMsg: 'تم إرسال كود التحقق إلى',
    verifyBtn: 'تحقق',
    resendBtn: 'أرسلوا الأيميل مرة ثانية',
    welcomeBack: 'مرحباً',
    carStatus: 'سيارتك مافيها شي!',
    myOrders: 'طلباتي',
    myGarage: 'كراجي',
    myWallet: 'المحفظة',
    walletBalance: 'رصيد المحفظة',
    aiStudio: 'استوديو AI',
    aiAssistant: 'مساعد AI',
    createRequest: 'إنشاء طلب جديد',
    newRequestDesc: 'احصل على مساعدة فورية',
    errorLogin: 'خطأ في المعلومات',
    errorFill: 'يرجى تعبئة جميع الحقول',
    errorPassMatch: 'الباسوورد غير متطابق',
    errorUserExists: 'اليوزر موجود بالفعل',
    errorEmailExists: 'ألأيميل موجود بالفعل',
    errorCode: 'الكود مو نفس اللي ارسلناه لك',
    msgCodeResent: 'تم إرسال الكود مرة أخرى',
    welcomeTitle: 'يا هلا!',
    notifications: 'الإشعارات',
    emptyNotifications: 'ما عندك إشعارات جديدة',
    errorUserLength: 'اسم المستخدم لازم يكون 4 حروف او اكثر',
    errorUserEng: 'اسم المستخدم لازم يكون انجليزي وارقام بس',
    errorEmail: 'تأكد من صيغة الايميل',
    errorPassLength: 'الباسوورد لازم يكون 8 خانات او اكثر',
    errorPassEng: 'الباسوورد لازم يكون حروف انجليزية',
    errorPassCap: 'لازم حرف كبير واحد على الاقل',
    errorPassNum: 'لازم رقم واحد على الاقل',
    back: 'رجوع',
    carType: 'نوع السيارة',
    searchPlaceholder: 'ابحث عن سيارتك...',
    selectYearPlaceholder: 'اختر السنة',
    workshopsTitle: 'الورش المتاحة',
    searchWorkshop: 'ابحث عن ورشة...',
    workshopDistance: 'كم',
    next: 'التالي',
    mapTitle: 'تحديد الوجهة',
    confirmLocation: 'تأكيد الموقع',
    distance: 'المسافة',
    calculating: 'جاري الحساب...',
    loading: 'جاري التحميل...',
    searchingFlatbed: 'جاري البحث عن سطحة...',
    backToDash: 'العودة للرئيسية',
    profileTitle: 'الملف الشخصي',
    memberSince: 'عضو منذ',
    emailProfile: 'البريد الإلكتروني',
    editProfile: 'تعديل الملف',
    accountSettings: 'إعدادات الحساب',
    logout: 'تسجيل خروج',
    rights: 'جميع الحقوق محفوظة كارفا',
    workTitle: 'للحين نشتغل ههه',
    nounUser: 'مستخدم',
    nounSat7a: 'سطحة',
    nounWorkshop: 'ورشة',
    flatbedOtherDest: 'إستعمال سطحة لوجهة أخرى',
    newBadge: 'جديد',
    // Order Tabs
    myOrdersTitle: 'طلباتي',
    tabCurrent: 'الحالية',
    tabCancelled: 'الملغية',
    tabCompleted: 'المكتملة',
    tabHistory: 'السابقة',
    currentOrders: 'طلباتي الحالية',
    previousOrders: 'طلباتي السابقة',
    orderDate: 'التاريخ',
    orderTime: 'الوقت',
    orderLocation: 'الموقع',
    // Garage
    addCar: 'أضف سيارة',
    editCar: 'تعديل السيارة',
    updateCar: 'تحديث السيارة',
    deleteCar: 'حذف السيارة',
    carColor: 'لون السيارة',
    plateNumber: 'رقم اللوحة',
    plateHint: ' (٣ حروف و ٤ أرقام بدون مسافات)',
    saveCar: 'حفظ السيارة',
    verifyCar: 'جاري التحقق...',
    uploadReg: 'إثبات الملكية',
    uploadRegDesc: 'هذه السيارة مسجلة مسبقاً. يرجى رفع صورة الاستمارة.',
    uploadBtn: 'رفع الاستمارة',
    verifyingAI: 'جاري التحقق عبر AI...',
    carAdded: 'تم إضافة السيارة بنجاح',
    maxCars: 'الحد الأقصى للسيارات 10',
    quickSelect: 'اختر من كراجي',
    areYouSure: 'هل أنت متأكد؟',
    confirmDeleteCar: 'سيتم حذف السيارة من كراجك.',
    confirmEditCar: 'سيتم تحديث بيانات السيارة.',
    yes: 'نعم',
    no: 'لا',
    carUpdated: 'تم تحديث السيارة بنجاح',
    carDeleted: 'تم حذف السيارة بنجاح',
    cancel: 'إلغاء',
    // Sat7a Dashboard
    searchRequests: 'البحث عن طلبات',
    requestHistory: 'تاريخ الطلبات',
    flatbedPlate: 'رقم لوحة السطحة',
    flatbedPhoto: 'صورة السطحة',
    uploadPhoto: 'رفع الصورة',
    uploadPhotoOptional: '(اختياري) رفع صورة السطحة',
    analyzingPhoto: 'جاري تحليل الصورة بالذكاء الاصطناعي...',
    // Sat7a Search Results
    searchResultsTitle: 'الطلبات المتاحة',
    noRequests: 'لا توجد طلبات قريبة منك حالياً',
    clientName: 'العميل',
    distanceToClient: 'المسافة إلي العميل',
    distanceToDest: 'المسافة إلي الوجهة',
    acceptRequest: 'قبول الطلب',
    rejectRequest: 'رفض الطلب',
    viewDetails: 'تفاصيل الطلب',
    km: 'كم',
    destination: 'الوجهة',
    destWorkshop: 'ورشة',
    destCustom: 'موقع محدد',
    // Matching Flow
    flatbedArrived: 'السطحة وصلت',
    flatbedArrivedUserBtn: 'السطحة وصلت',
    flatbedArrivedSat7aBtn: 'وصلت للمستخدم!',
    confirmArrivalMsg: 'وصلت؟',
    confirmArrivalYes: 'أيه',
    confirmArrivalNo: 'لا',
    arrivedClient: 'وصلت للعميل!',
    arrivedDest: 'وصلت للوجهة!',
    arrivedWorkshop: 'وصلت للورشة',
    headingToDest: 'في الطريق إلى الوجهة...',
    cancelOrder: 'إلغاء الطلب',
    chat: 'محادثة',
    driverName: 'اسم السائق',
    driverPlate: 'رقم اللوحة',
    waitingForConfirmation: 'بإنتظار الطرف الاخر',
    requestAccepted: 'تم قبول طلبك!',
    driverOnWay: 'السطحة بطريقها للزبون!',
    pageLTitle: 'تم التوصيل بنجاح!',
    pageRTitle: 'وصلت السطحة!',
    chatTitle: 'المحادثة',
    typeMessage: 'اكتب رسالتك...',
    send: 'إرسال',
    you: 'أنت',
    driver: 'السائق',
    leaveChat: 'مغادرة المحادثة',
    image: 'صورة',
    selectImage: 'اختر صورة',
    // Workshop Signup
    workshopNameLabel: 'اسم الورشة',
    workshopPhoneLabel: 'رقم هاتف الورشة',
    workshopLocationLabel: 'موقع الورشة',
    pickLocation: 'تحديد الموقع علي الخريطة',
    locationSelected: 'تم تحديد الموقع',
    commercialRegLabel: 'السجل التجاري (اختياري)',
    municipalLicenseLabel: 'الترخيص البلدي (اختياري)',
    uploadFile: 'رفع ملف',
    fileUploaded: 'تم الرفع',
    // Problem Description
    probDescTitle: 'وصف المشكلة',
    probDescPlaceholder: 'اشرح المشكلة اللي تواجهها...',
    incidentTime: 'وقت الحدوث',
    isAccident: 'هل هو حادث؟',
    accidentReport: 'تقرير الحادث',
    carPhotoOptional: 'صورة السيارة (اختياري)',
    requestDetails: 'تفاصيل الطلب',
    canDriveLabel: 'هل تقدر تمشي بالسيارة للورشة؟',
    // Billing & Negotiation
    billTitle: 'الفاتورة',
    addItem: 'إضافة عنصر',
    itemName: 'اسم القطعة / الخدمة',
    itemPrice: 'السعر',
    itemQty: 'العدد',
    laborCost: 'سعر شغل اليد',
    total: 'المجموع',
    agreeBill: 'موافق واعتماد الفاتورة',
    payNow: 'أدفع الان',
    negotiating: 'جاري الاتفاق مع الورشة',
    sar: 'ريال',
    resumeOrder: 'متابعة الطلب',
    // Sat7a Tabs
    tabRequests: 'الطلبات',
    tabMyOrders: 'طلباتي',
    // Workshop Tabs & Notifications
    tabMessages: 'الرسائل',
    billAccepted: 'قد وافق على المبلغ',
    newMessages: 'رسائل جديدة',
    userAtWorkshop: 'المستخدم عندك!',
    // Payment
    paymentTitle: 'دفع تكلفة المشوار',
    tripCost: 'تكلفة الرحلة',
    pay: 'دفع',
    insufficientFunds: 'رصيد غير كافي',
    paymentSuccess: 'تم الدفع بنجاح',
    waitingPayment: 'بإنتظار دفع المستخدم',
    paymentComplete: 'تم استلام الدفعة',
    // User Tabs
    tabHome: 'الرئيسية',
    searchingStatus: 'جاري البحث عن سطحة...',
  },
  en: {
    appTitle: 'CARVA',
    login: 'Sign In',
    signup: 'Create Account',
    guest: 'Continue as Guest',
    support: 'Support',
    about: 'About Us',
    help: 'Help',
    loginTitle: 'Sign In',
    loginIdentifier: 'Username or Email',
    password: 'Password',
    enter: 'Login',
    roleTitle: 'Welcome! Tell us about you',
    roleSat7a: 'Flatbed Lorry',
    roleUser: 'I am User',
    roleWorkshop: 'I am Workshop',
    detailsTitle: 'Details',
    nameLabel: 'Name?',
    usernameLabel: 'Username?',
    emailLabel: 'Email?',
    passwordLabel: 'Password?',
    confirmPasswordLabel: 'Confirm Password?',
    register: 'Register',
    verifyTitle: 'Verify Account',
    verifyMsg: 'Verification code sent to',
    verifyBtn: 'Verify',
    resendBtn: 'Resend Email',
    welcomeBack: 'Welcome back,',
    carStatus: 'Your car is running fine!',
    myOrders: 'My Orders',
    myGarage: 'My Garage',
    myWallet: 'Wallet',
    walletBalance: 'Wallet Balance',
    aiStudio: 'AI Studio',
    aiAssistant: 'AI Assistant',
    createRequest: 'Create New Request',
    newRequestDesc: 'Get immediate help',
    errorLogin: 'Invalid credentials',
    errorFill: 'Please fill all fields',
    errorPassMatch: 'Passwords do not match',
    errorUserExists: 'Username already exists',
    errorEmailExists: 'Email already exists',
    errorCode: 'Incorrect code',
    msgCodeResent: 'Code resent successfully',
    welcomeTitle: 'Welcome!',
    notifications: 'Notifications',
    emptyNotifications: 'No new notifications',
    errorUserLength: 'Username must be at least 4 chars',
    errorUserEng: 'Username must be English letters/numbers only',
    errorEmail: 'Invalid email format',
    errorPassLength: 'Password must be at least 8 chars',
    errorPassEng: 'Password must be English characters',
    errorPassCap: 'At least 1 Uppercase letter',
    errorPassNum: 'At least 1 Number',
    back: 'Back',
    carType: 'Car Type',
    searchPlaceholder: 'Search for your car...',
    selectYearPlaceholder: 'Select Year',
    workshopsTitle: 'Available Workshops',
    searchWorkshop: 'Search workshop...',
    workshopDistance: 'km',
    next: 'Next',
    mapTitle: 'Select Destination',
    confirmLocation: 'Confirm Location',
    distance: 'Distance',
    calculating: 'Calculating...',
    loading: 'Loading...',
    searchingFlatbed: 'Searching for flatbed...',
    backToDash: 'Back to Dashboard',
    profileTitle: 'Profile',
    memberSince: 'Member Since',
    emailProfile: 'Email',
    editProfile: 'Edit Profile',
    accountSettings: 'Account Settings',
    logout: 'Logout',
    rights: 'All rights reserved Carva',
    workTitle: 'Work in progress lol',
    nounUser: 'Customer',
    nounSat7a: 'Flatbed',
    nounWorkshop: 'Workshop',
    flatbedOtherDest: 'Use flatbed for another destination',
    newBadge: 'NEW',
    // Order Tabs
    myOrdersTitle: 'My Orders',
    tabCurrent: 'Current',
    tabCancelled: 'Cancelled Orders',
    tabCompleted: 'Completed Orders',
    tabHistory: 'History',
    currentOrders: 'Current Orders',
    previousOrders: 'Previous Orders',
    orderDate: 'Date',
    orderTime: 'Time',
    orderLocation: 'Location',
    // Garage
    addCar: 'Add Car',
    editCar: 'Edit Car',
    updateCar: 'Update Car',
    deleteCar: 'Delete Car',
    carColor: 'Car Color',
    plateNumber: 'Plate Number',
    plateHint: ' (3 letters & 4 numbers, no spaces)',
    saveCar: 'Save Car',
    verifyCar: 'Verifying...',
    uploadReg: 'Proof of Ownership',
    uploadRegDesc: 'This car is already registered. Please upload registration.',
    uploadBtn: 'Upload Registration',
    verifyingAI: 'Verifying via AI...',
    carAdded: 'Car added successfully',
    maxCars: 'Max limit 10 cars',
    quickSelect: 'Quick Select from Garage',
    areYouSure: 'Are you sure?',
    confirmDeleteCar: 'This car will be removed from your garage.',
    confirmEditCar: 'Car details will be updated.',
    yes: 'Yes',
    no: 'No',
    carUpdated: 'Car updated successfully',
    carDeleted: 'Car deleted successfully',
    cancel: 'Cancel',
    // Sat7a Dashboard
    searchRequests: 'Search for Requests',
    requestHistory: 'Request History',
    flatbedPlate: 'Flatbed Plate Number',
    flatbedPhoto: 'Flatbed Photo',
    uploadPhoto: 'Upload Photo',
    uploadPhotoOptional: '(Optional) Upload Flatbed Photo',
    analyzingPhoto: 'Analyzing photo via AI...',
    // Sat7a Search Results
    searchResultsTitle: 'Available Requests',
    noRequests: 'No requests near you at the moment',
    clientName: 'Client',
    distanceToClient: 'Distance to Client',
    distanceToDest: 'Distance to Destination',
    acceptRequest: 'Accept Request',
    rejectRequest: 'Reject',
    viewDetails: 'Order Details',
    km: 'km',
    destination: 'Destination',
    destWorkshop: 'Workshop',
    destCustom: 'Custom Location',
    // Matching Flow
    flatbedArrived: 'Flatbed Arrived',
    flatbedArrivedUserBtn: 'Flatbed Arrived',
    flatbedArrivedSat7aBtn: 'Arrived at User!',
    confirmArrivalMsg: 'Arrived?',
    confirmArrivalYes: 'Yeah',
    confirmArrivalNo: 'No',
    arrivedClient: 'Arrived at Client!',
    arrivedDest: 'Arrived at Destination!',
    arrivedWorkshop: 'Arrived at Workshop',
    headingToDest: 'Heading to Destination...',
    cancelOrder: 'Cancel Order',
    chat: 'Chat',
    driverName: 'Driver Name',
    driverPlate: 'Plate Number',
    waitingForConfirmation: 'Waiting for other party',
    requestAccepted: 'Request Accepted!',
    driverOnWay: 'Flatbed is on the way to customer!',
    pageLTitle: 'Delivered Successfully!',
    pageRTitle: 'Flatbed Arrived!',
    chatTitle: 'Chat',
    typeMessage: 'Type a message...',
    send: 'Send',
    you: 'You',
    driver: 'Driver',
    leaveChat: 'Leave Chat',
    image: 'Image',
    selectImage: 'Select Image',
    // Workshop Signup
    workshopNameLabel: 'Workshop Name',
    workshopPhoneLabel: 'Workshop Phone',
    workshopLocationLabel: 'Workshop Location',
    pickLocation: 'Pick Location on Map',
    locationSelected: 'Location Selected',
    commercialRegLabel: 'Commercial Registration (Optional)',
    municipalLicenseLabel: 'Municipal License (Optional)',
    uploadFile: 'Upload File',
    fileUploaded: 'File Uploaded',
    // Problem Description
    probDescTitle: 'Problem Description',
    probDescPlaceholder: 'Describe the problem you are facing...',
    incidentTime: 'Time of Incident',
    isAccident: 'Is it an Accident?',
    accidentReport: 'Accident Report',
    carPhotoOptional: 'Car Photo (Optional)',
    requestDetails: 'Request Details',
    canDriveLabel: 'Can you drive the car to the workshop?',
    // Billing & Negotiation
    billTitle: 'Invoice',
    addItem: 'Add Item',
    itemName: 'Item/Service Name',
    itemPrice: 'Price',
    itemQty: 'Qty',
    laborCost: 'Labor Cost',
    total: 'Total',
    agreeBill: 'Agree & Confirm Invoice',
    payNow: 'Pay Now',
    negotiating: 'Negotiating with Workshop',
    sar: 'SAR',
    resumeOrder: 'Resume Order',
    // Sat7a Tabs
    tabRequests: 'Requests',
    tabMyOrders: 'My Orders',
    // Workshop Tabs & Notifications
    tabMessages: 'Messages',
    billAccepted: 'accepted the amount',
    newMessages: 'New Messages',
    userAtWorkshop: 'User is here!',
    // Payment
    paymentTitle: 'Pay for Trip',
    tripCost: 'Trip Cost',
    pay: 'Pay',
    insufficientFunds: 'Insufficient Funds',
    paymentSuccess: 'Payment Successful',
    waitingPayment: 'Waiting for user payment',
    paymentComplete: 'Payment Received',
    // User Tabs
    tabHome: 'Home',
    searchingStatus: 'Searching for flatbed...',
  }
};